export const ADD_BOOK_ERROR='ADD_BOOK_ERROR';
export  const ADD_BOOK_LOADING='ADD_BOOK_LOADING'; 
export  const ADD_BOOK_SUCCESS='ADD_BOOK_SUCCESS';  


export const DELETE_BOOK_ERROR='DELETE_BOOK_ERROR';
export  const DELETE_BOOK_LOADING='DELETE_BOOK_LOADING'; 
export  const DELETE_BOOK_SUCCESS='DELETE_BOOK_SUCCESS';  



export const EDIT_BOOK_ERROR='EDIT_BOOK_ERROR';
export  const EDIT_BOOK_LOADING='EDIT_BOOK_LOADING'; 
export  const EDIT_BOOK_SUCCESS='EDIT_BOOK_SUCCESS';  


export const FETCH_BOOK_ERROR='FETCH_BOOK_ERROR';
export  const FETCH_BOOK_LOADING='FETCH_BOOK_LOADING'; 
export  const FETCH_BOOK_SUCCESS='FETCH_BOOK_SUCCESS';  

